import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "Terms of Service for Alaii Engage — AI Social Media Engagement Automation",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <nav className="flex items-center justify-between max-w-4xl mx-auto px-6 py-5">
        <Link href="/landing" className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-xl bg-gradient-to-br from-[#4A9FD4] to-[#63B3E4] flex items-center justify-center">
            <span className="text-white font-bold text-sm">A</span>
          </div>
          <span className="text-lg font-bold" style={{ color: "var(--text-primary, #1e293b)" }}>Alaii Engage</span>
        </Link>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-12 prose prose-slate" style={{ color: "var(--text-primary, #1e293b)" }}>
        <h1>Terms of Service</h1>
        <p className="text-sm" style={{ color: "var(--text-muted, #94a3b8)" }}>Last updated: March 18, 2026</p>

        <h2>1. Acceptance</h2>
        <p>By creating an account or using the Alaii Engage API, you agree to these terms. If you do not agree, do not use our service.</p>

        <h2>2. Description of Service</h2>
        <p>Alaii Engage is an AI-powered social media engagement platform. We generate human-like content (comments, replies, DMs) and, with your authorization, post it on your connected social media accounts via official platform APIs.</p>

        <h2>3. Your Responsibilities</h2>
        <ul>
          <li>You are responsible for all activity on your account</li>
          <li>You must comply with each social media platform&apos;s terms of service</li>
          <li>You must not use our service to harass, spam, or deceive others</li>
          <li>You must not use our service for illegal purposes</li>
          <li>You are responsible for reviewing AI-generated content before it is posted on your behalf</li>
        </ul>

        <h2>4. AI-Generated Content</h2>
        <p>Content generated by our AI is provided as suggestions. While we strive for quality and appropriateness, AI may occasionally produce content that is inaccurate or inappropriate. You are ultimately responsible for content posted on your social media accounts.</p>

        <h2>5. Account Eligibility</h2>
        <ul>
          <li>You must be at least 18 years old</li>
          <li>You must provide accurate account information</li>
          <li>You may not create multiple accounts to circumvent usage limits</li>
        </ul>

        <h2>6. Pricing &amp; Billing</h2>
        <ul>
          <li><strong>Free plan</strong>: 100 API calls per month, no charge</li>
          <li><strong>Pro plan</strong>: $40/month for 10,000 API calls</li>
          <li><strong>Agency plan</strong>: $99/month for 50,000 API calls</li>
        </ul>
        <p>Paid plans are billed monthly via Stripe. You may cancel at any time. Refunds are provided on a case-by-case basis for the current billing period.</p>

        <h2>7. API Usage</h2>
        <p>API keys are personal and should not be shared. We reserve the right to revoke API access for abuse, including but not limited to: exceeding rate limits, generating harmful content, or violating platform terms of service.</p>

        <h2>8. Intellectual Property</h2>
        <p>You own the content generated through our service. We retain no rights to content posted on your social media accounts. Our platform, brand, and technology remain our intellectual property.</p>

        <h2>9. Limitation of Liability</h2>
        <p>Alaii Engage is provided &quot;as is.&quot; We are not liable for: social media account suspensions resulting from automated engagement, content generated by AI that causes harm, or service interruptions. Our total liability is limited to the amount you paid us in the 12 months preceding the claim.</p>

        <h2>10. Platform Compliance</h2>
        <p>We use official platform APIs (Instagram Graph API, X API v2, Reddit API, TikTok API, LinkedIn API, Facebook Graph API) and comply with each platform&apos;s developer policies. However, social media platforms may change their policies at any time, which may affect our service availability.</p>

        <h2>11. Termination</h2>
        <p>We may suspend or terminate your account if you violate these terms. You may delete your account at any time via Settings. Upon deletion, we will remove your data within 30 days.</p>

        <h2>12. Changes</h2>
        <p>We may update these terms. Material changes will be communicated via email or in-app notification at least 14 days before taking effect.</p>

        <h2>13. Contact</h2>
        <p>Questions? Email <strong>legal@alaii.com</strong></p>
      </article>
    </div>
  );
}
